# --- DATABASE CREDENTIALS ---
DB_CONFIG = {
    "dbname": "india_weather_db",
    "user": "postgres",
    "password": "200424",  # Update with your local password
    "host": "localhost",
    "port": "5432",
}

# --- ALL 28 STATES: 9-POINT REGIONAL GRID (252 ZONES) ---
INDIA_WEATHER_GRID = [
    # --- 1. ANDHRA PRADESH ---
    {
        "state": "Andhra Pradesh",
        "zone": "North",
        "city": "Srikakulam",
        "lat": 18.2949,
        "lon": 83.8938,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "North-East",
        "city": "Visakhapatnam",
        "lat": 17.6868,
        "lon": 83.2185,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "North-West",
        "city": "Kurnool",
        "lat": 15.8281,
        "lon": 78.0373,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "Center",
        "city": "Vijayawada",
        "lat": 16.5062,
        "lon": 80.6480,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "East",
        "city": "Kakinada",
        "lat": 16.9891,
        "lon": 82.2475,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "West",
        "city": "Anantapur",
        "lat": 14.6819,
        "lon": 77.6006,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "South",
        "city": "Tirupati",
        "lat": 13.6288,
        "lon": 79.4192,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "South-East",
        "city": "Nellore",
        "lat": 14.4426,
        "lon": 79.9865,
    },
    {
        "state": "Andhra Pradesh",
        "zone": "South-West",
        "city": "Kadapa",
        "lat": 14.4673,
        "lon": 78.8242,
    },
    # --- 2. ARUNACHAL PRADESH ---
    {
        "state": "Arunachal Pradesh",
        "zone": "North",
        "city": "Tawang",
        "lat": 27.5856,
        "lon": 91.8596,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "North-East",
        "city": "Anjaw",
        "lat": 28.1189,
        "lon": 96.3486,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "North-West",
        "city": "Seppa",
        "lat": 27.3292,
        "lon": 93.0360,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "Center",
        "city": "Ziro",
        "lat": 27.5925,
        "lon": 93.8290,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "East",
        "city": "Tezu",
        "lat": 27.9159,
        "lon": 96.1669,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "West",
        "city": "Bomdila",
        "lat": 27.2650,
        "lon": 92.4172,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "South",
        "city": "Itanagar",
        "lat": 27.0844,
        "lon": 93.6053,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "South-East",
        "city": "Changlang",
        "lat": 27.1420,
        "lon": 95.7594,
    },
    {
        "state": "Arunachal Pradesh",
        "zone": "South-West",
        "city": "Pasighat",
        "lat": 28.0673,
        "lon": 95.3275,
    },
    # --- 3. ASSAM ---
    {
        "state": "Assam",
        "zone": "North",
        "city": "North Lakhimpur",
        "lat": 27.2345,
        "lon": 94.1039,
    },
    {
        "state": "Assam",
        "zone": "North-East",
        "city": "Dibrugarh",
        "lat": 27.4728,
        "lon": 94.9120,
    },
    {
        "state": "Assam",
        "zone": "North-West",
        "city": "Kokrajhar",
        "lat": 26.3917,
        "lon": 90.2743,
    },
    {
        "state": "Assam",
        "zone": "Center",
        "city": "Nagaon",
        "lat": 26.3475,
        "lon": 92.6841,
    },
    {
        "state": "Assam",
        "zone": "East",
        "city": "Tinsukia",
        "lat": 27.4915,
        "lon": 95.5611,
    },
    {
        "state": "Assam",
        "zone": "West",
        "city": "Bongaigaon",
        "lat": 26.4746,
        "lon": 90.5480,
    },
    {
        "state": "Assam",
        "zone": "South",
        "city": "Silchar",
        "lat": 24.8333,
        "lon": 92.7789,
    },
    {
        "state": "Assam",
        "zone": "South-East",
        "city": "Diphu",
        "lat": 25.8451,
        "lon": 93.4371,
    },
    {
        "state": "Assam",
        "zone": "South-West",
        "city": "Guwahati",
        "lat": 26.1445,
        "lon": 91.7362,
    },
    # --- 4. BIHAR ---
    {
        "state": "Bihar",
        "zone": "North",
        "city": "Sitamarhi",
        "lat": 26.5910,
        "lon": 85.4851,
    },
    {
        "state": "Bihar",
        "zone": "North-East",
        "city": "Purnia",
        "lat": 25.7771,
        "lon": 87.4753,
    },
    {
        "state": "Bihar",
        "zone": "North-West",
        "city": "Bettiah",
        "lat": 26.8025,
        "lon": 84.5074,
    },
    {
        "state": "Bihar",
        "zone": "Center",
        "city": "Patna",
        "lat": 25.5941,
        "lon": 85.1376,
    },
    {
        "state": "Bihar",
        "zone": "East",
        "city": "Katihar",
        "lat": 25.5414,
        "lon": 87.5758,
    },
    {
        "state": "Bihar",
        "zone": "West",
        "city": "Buxar",
        "lat": 25.5600,
        "lon": 83.9785,
    },
    {
        "state": "Bihar",
        "zone": "South",
        "city": "Gaya",
        "lat": 24.7914,
        "lon": 85.0002,
    },
    {
        "state": "Bihar",
        "zone": "South-East",
        "city": "Bhagalpur",
        "lat": 25.2425,
        "lon": 87.0171,
    },
    {
        "state": "Bihar",
        "zone": "South-West",
        "city": "Sasaram",
        "lat": 24.9507,
        "lon": 84.0152,
    },
    # --- 5. CHHATTISGARH ---
    {
        "state": "Chhattisgarh",
        "zone": "North",
        "city": "Ambikapur",
        "lat": 23.1181,
        "lon": 83.1990,
    },
    {
        "state": "Chhattisgarh",
        "zone": "North-East",
        "city": "Raigarh",
        "lat": 21.8974,
        "lon": 83.3950,
    },
    {
        "state": "Chhattisgarh",
        "zone": "North-West",
        "city": "Kanker",
        "lat": 20.2764,
        "lon": 81.4907,
    },
    {
        "state": "Chhattisgarh",
        "zone": "Center",
        "city": "Raipur",
        "lat": 21.2514,
        "lon": 81.6296,
    },
    {
        "state": "Chhattisgarh",
        "zone": "East",
        "city": "Mahasamund",
        "lat": 21.1077,
        "lon": 82.1031,
    },
    {
        "state": "Chhattisgarh",
        "zone": "West",
        "city": "Rajnandgaon",
        "lat": 21.0970,
        "lon": 81.0347,
    },
    {
        "state": "Chhattisgarh",
        "zone": "South",
        "city": "Jagdalpur",
        "lat": 19.0749,
        "lon": 82.0305,
    },
    {
        "state": "Chhattisgarh",
        "zone": "South-East",
        "city": "Dantewada",
        "lat": 18.8953,
        "lon": 81.3533,
    },
    {
        "state": "Chhattisgarh",
        "zone": "South-West",
        "city": "Bijapur",
        "lat": 18.7963,
        "lon": 80.8140,
    },
    # --- 6. GOA ---
    {
        "state": "Goa",
        "zone": "North",
        "city": "Pernem",
        "lat": 15.7265,
        "lon": 73.7937,
    },
    {
        "state": "Goa",
        "zone": "North-East",
        "city": "Bicholim",
        "lat": 15.5804,
        "lon": 73.9538,
    },
    {
        "state": "Goa",
        "zone": "North-West",
        "city": "Mapusa",
        "lat": 15.5905,
        "lon": 73.8130,
    },
    {
        "state": "Goa",
        "zone": "Center",
        "city": "Panaji",
        "lat": 15.4909,
        "lon": 73.8278,
    },
    {
        "state": "Goa",
        "zone": "East",
        "city": "Sanquelim",
        "lat": 15.5457,
        "lon": 73.9318,
    },
    {
        "state": "Goa",
        "zone": "West",
        "city": "Calangute",
        "lat": 15.5435,
        "lon": 73.7554,
    },
    {
        "state": "Goa",
        "zone": "South",
        "city": "Margao",
        "lat": 15.2832,
        "lon": 73.9562,
    },
    {
        "state": "Goa",
        "zone": "South-East",
        "city": "Curchorem",
        "lat": 15.2514,
        "lon": 74.1089,
    },
    {
        "state": "Goa",
        "zone": "South-West",
        "city": "Vasco da Gama",
        "lat": 15.3996,
        "lon": 73.8139,
    },
    # --- 7. GUJARAT ---
    {
        "state": "Gujarat",
        "zone": "North",
        "city": "Palanpur",
        "lat": 24.1724,
        "lon": 72.4340,
    },
    {
        "state": "Gujarat",
        "zone": "North-East",
        "city": "Himmatnagar",
        "lat": 23.6033,
        "lon": 72.9691,
    },
    {
        "state": "Gujarat",
        "zone": "North-West",
        "city": "Bhuj",
        "lat": 23.2420,
        "lon": 69.6669,
    },
    {
        "state": "Gujarat",
        "zone": "Center",
        "city": "Ahmedabad",
        "lat": 23.0225,
        "lon": 72.5714,
    },
    {
        "state": "Gujarat",
        "zone": "East",
        "city": "Godhra",
        "lat": 22.7758,
        "lon": 73.6186,
    },
    {
        "state": "Gujarat",
        "zone": "West",
        "city": "Jamnagar",
        "lat": 22.4707,
        "lon": 70.0577,
    },
    {
        "state": "Gujarat",
        "zone": "South",
        "city": "Valsad",
        "lat": 20.6128,
        "lon": 72.9373,
    },
    {
        "state": "Gujarat",
        "zone": "South-East",
        "city": "Surat",
        "lat": 21.1702,
        "lon": 72.8311,
    },
    {
        "state": "Gujarat",
        "zone": "South-West",
        "city": "Veraval",
        "lat": 20.9037,
        "lon": 70.3649,
    },
    # --- 8. HARYANA ---
    {
        "state": "Haryana",
        "zone": "North",
        "city": "Ambala",
        "lat": 30.3782,
        "lon": 76.7767,
    },
    {
        "state": "Haryana",
        "zone": "North-East",
        "city": "Yamunanagar",
        "lat": 30.1290,
        "lon": 77.2674,
    },
    {
        "state": "Haryana",
        "zone": "North-West",
        "city": "Sirsa",
        "lat": 29.5352,
        "lon": 75.0210,
    },
    {
        "state": "Haryana",
        "zone": "Center",
        "city": "Rohtak",
        "lat": 28.8955,
        "lon": 76.6066,
    },
    {
        "state": "Haryana",
        "zone": "East",
        "city": "Faridabad",
        "lat": 28.4089,
        "lon": 77.3178,
    },
    {
        "state": "Haryana",
        "zone": "West",
        "city": "Hisar",
        "lat": 29.1492,
        "lon": 75.7217,
    },
    {
        "state": "Haryana",
        "zone": "South",
        "city": "Palwal",
        "lat": 28.1454,
        "lon": 77.3323,
    },
    {
        "state": "Haryana",
        "zone": "South-East",
        "city": "Gurugram",
        "lat": 28.4595,
        "lon": 77.0266,
    },
    {
        "state": "Haryana",
        "zone": "South-West",
        "city": "Narnaul",
        "lat": 28.0434,
        "lon": 76.1084,
    },
    # --- 9. HIMACHAL PRADESH ---
    {
        "state": "Himachal Pradesh",
        "zone": "North",
        "city": "Keylong",
        "lat": 32.5711,
        "lon": 77.0423,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "North-East",
        "city": "Kalpa",
        "lat": 31.5434,
        "lon": 78.2536,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "North-West",
        "city": "Chamba",
        "lat": 32.5534,
        "lon": 76.1287,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "Center",
        "city": "Mandi",
        "lat": 31.7087,
        "lon": 76.9317,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "East",
        "city": "Rampur",
        "lat": 31.4487,
        "lon": 77.6322,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "West",
        "city": "Kangra",
        "lat": 32.0998,
        "lon": 76.2691,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "South",
        "city": "Shimla",
        "lat": 31.1048,
        "lon": 77.1734,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "South-East",
        "city": "Nahan",
        "lat": 30.5598,
        "lon": 77.2952,
    },
    {
        "state": "Himachal Pradesh",
        "zone": "South-West",
        "city": "Una",
        "lat": 31.4683,
        "lon": 76.2708,
    },
    # --- 10. JHARKHAND ---
    {
        "state": "Jharkhand",
        "zone": "North",
        "city": "Deoghar",
        "lat": 24.4826,
        "lon": 86.6955,
    },
    {
        "state": "Jharkhand",
        "zone": "North-East",
        "city": "Sahibganj",
        "lat": 25.2492,
        "lon": 87.6443,
    },
    {
        "state": "Jharkhand",
        "zone": "North-West",
        "city": "Daltonganj",
        "lat": 24.0375,
        "lon": 84.0754,
    },
    {
        "state": "Jharkhand",
        "zone": "Center",
        "city": "Ranchi",
        "lat": 23.3441,
        "lon": 85.3096,
    },
    {
        "state": "Jharkhand",
        "zone": "East",
        "city": "Dhanbad",
        "lat": 23.7957,
        "lon": 86.4304,
    },
    {
        "state": "Jharkhand",
        "zone": "West",
        "city": "Gumla",
        "lat": 23.0454,
        "lon": 85.5422,
    },
    {
        "state": "Jharkhand",
        "zone": "South",
        "city": "Chaibasa",
        "lat": 22.5557,
        "lon": 85.8080,
    },
    {
        "state": "Jharkhand",
        "zone": "South-East",
        "city": "Jamshedpur",
        "lat": 22.8046,
        "lon": 86.2029,
    },
    {
        "state": "Jharkhand",
        "zone": "South-West",
        "city": "Simdega",
        "lat": 22.6186,
        "lon": 84.5050,
    },
    # --- 11. KARNATAKA ---
    {
        "state": "Karnataka",
        "zone": "North",
        "city": "Bagalkot",
        "lat": 16.1833,
        "lon": 75.7000,
    },
    {
        "state": "Karnataka",
        "zone": "North-East",
        "city": "Kalaburagi",
        "lat": 17.3297,
        "lon": 76.8343,
    },
    {
        "state": "Karnataka",
        "zone": "North-West",
        "city": "Belagavi",
        "lat": 15.8497,
        "lon": 74.4977,
    },
    {
        "state": "Karnataka",
        "zone": "Center",
        "city": "Davangere",
        "lat": 14.4644,
        "lon": 75.9218,
    },
    {
        "state": "Karnataka",
        "zone": "East",
        "city": "Kolar",
        "lat": 13.1367,
        "lon": 78.1292,
    },
    {
        "state": "Karnataka",
        "zone": "West",
        "city": "Mangaluru",
        "lat": 12.9141,
        "lon": 74.8560,
    },
    {
        "state": "Karnataka",
        "zone": "South",
        "city": "Mysuru",
        "lat": 12.2958,
        "lon": 76.6394,
    },
    {
        "state": "Karnataka",
        "zone": "South-East",
        "city": "Bengaluru",
        "lat": 12.9716,
        "lon": 77.5946,
    },
    {
        "state": "Karnataka",
        "zone": "South-West",
        "city": "Hassan",
        "lat": 13.0068,
        "lon": 76.1004,
    },
    # --- 12. KERALA ---
    {
        "state": "Kerala",
        "zone": "North",
        "city": "Kannur",
        "lat": 11.8745,
        "lon": 75.3704,
    },
    {
        "state": "Kerala",
        "zone": "North-East",
        "city": "Kalpetta",
        "lat": 11.6085,
        "lon": 76.0822,
    },
    {
        "state": "Kerala",
        "zone": "North-West",
        "city": "Kasaragod",
        "lat": 12.5020,
        "lon": 74.9870,
    },
    {
        "state": "Kerala",
        "zone": "Center",
        "city": "Thrissur",
        "lat": 10.5276,
        "lon": 76.2144,
    },
    {
        "state": "Kerala",
        "zone": "East",
        "city": "Munnar",
        "lat": 10.0889,
        "lon": 77.0595,
    },
    {
        "state": "Kerala",
        "zone": "West",
        "city": "Kozhikode",
        "lat": 11.2588,
        "lon": 75.7804,
    },
    {
        "state": "Kerala",
        "zone": "South",
        "city": "Thiruvananthapuram",
        "lat": 8.5241,
        "lon": 76.9366,
    },
    {
        "state": "Kerala",
        "zone": "South-East",
        "city": "Punalur",
        "lat": 9.0140,
        "lon": 76.9248,
    },
    {
        "state": "Kerala",
        "zone": "South-West",
        "city": "Kochi",
        "lat": 9.9312,
        "lon": 76.2673,
    },
    # --- 13. MADHYA PRADESH ---
    {
        "state": "Madhya Pradesh",
        "zone": "North",
        "city": "Gwalior",
        "lat": 26.2183,
        "lon": 78.1828,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "North-East",
        "city": "Rewa",
        "lat": 24.5362,
        "lon": 81.3037,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "North-West",
        "city": "Shivpuri",
        "lat": 25.4239,
        "lon": 77.6620,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "Center",
        "city": "Bhopal",
        "lat": 23.2599,
        "lon": 77.4126,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "East",
        "city": "Jabalpur",
        "lat": 23.1815,
        "lon": 79.9864,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "West",
        "city": "Indore",
        "lat": 22.7196,
        "lon": 75.8577,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "South",
        "city": "Betul",
        "lat": 21.9168,
        "lon": 77.9009,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "South-East",
        "city": "Mandla",
        "lat": 22.5971,
        "lon": 80.3705,
    },
    {
        "state": "Madhya Pradesh",
        "zone": "South-West",
        "city": "Khargone",
        "lat": 21.8219,
        "lon": 75.6111,
    },
    # --- 14. MAHARASHTRA ---
    {
        "state": "Maharashtra",
        "zone": "North",
        "city": "Dhule",
        "lat": 20.9042,
        "lon": 74.7749,
    },
    {
        "state": "Maharashtra",
        "zone": "North-East",
        "city": "Nagpur",
        "lat": 21.1458,
        "lon": 79.0882,
    },
    {
        "state": "Maharashtra",
        "zone": "North-West",
        "city": "Nashik",
        "lat": 19.9975,
        "lon": 73.7898,
    },
    {
        "state": "Maharashtra",
        "zone": "Center",
        "city": "Ahmednagar",
        "lat": 19.0952,
        "lon": 74.7496,
    },
    {
        "state": "Maharashtra",
        "zone": "East",
        "city": "Chandrapur",
        "lat": 19.9615,
        "lon": 79.2961,
    },
    {
        "state": "Maharashtra",
        "zone": "West",
        "city": "Mumbai",
        "lat": 19.0760,
        "lon": 72.8777,
    },
    {
        "state": "Maharashtra",
        "zone": "South",
        "city": "Kolhapur",
        "lat": 16.7050,
        "lon": 74.2433,
    },
    {
        "state": "Maharashtra",
        "zone": "South-East",
        "city": "Solapur",
        "lat": 17.6599,
        "lon": 75.9064,
    },
    {
        "state": "Maharashtra",
        "zone": "South-West",
        "city": "Pune",
        "lat": 18.5204,
        "lon": 73.8567,
    },
    # --- 15. MANIPUR ---
    {
        "state": "Manipur",
        "zone": "North",
        "city": "Senapati",
        "lat": 25.3129,
        "lon": 94.0202,
    },
    {
        "state": "Manipur",
        "zone": "North-East",
        "city": "Ukhrul",
        "lat": 25.1119,
        "lon": 94.3639,
    },
    {
        "state": "Manipur",
        "zone": "North-West",
        "city": "Kangpokpi",
        "lat": 25.1812,
        "lon": 93.9669,
    },
    {
        "state": "Manipur",
        "zone": "Center",
        "city": "Imphal",
        "lat": 24.8170,
        "lon": 93.9368,
    },
    {
        "state": "Manipur",
        "zone": "East",
        "city": "Kamjong",
        "lat": 24.8988,
        "lon": 94.4988,
    },
    {
        "state": "Manipur",
        "zone": "West",
        "city": "Tamenglong",
        "lat": 24.9866,
        "lon": 93.4913,
    },
    {
        "state": "Manipur",
        "zone": "South",
        "city": "Churachandpur",
        "lat": 24.3411,
        "lon": 93.6708,
    },
    {
        "state": "Manipur",
        "zone": "South-East",
        "city": "Chandel",
        "lat": 24.3312,
        "lon": 94.0163,
    },
    {
        "state": "Manipur",
        "zone": "South-West",
        "city": "Pherzawl",
        "lat": 24.3323,
        "lon": 93.2678,
    },
    # --- 16. MEGHALAYA ---
    {
        "state": "Meghalaya",
        "zone": "North",
        "city": "Nongpoh",
        "lat": 25.9038,
        "lon": 91.8797,
    },
    {
        "state": "Meghalaya",
        "zone": "North-East",
        "city": "Jowai",
        "lat": 25.5991,
        "lon": 92.2036,
    },
    {
        "state": "Meghalaya",
        "zone": "North-West",
        "city": "Tura",
        "lat": 25.5141,
        "lon": 90.2185,
    },
    {
        "state": "Meghalaya",
        "zone": "Center",
        "city": "Shillong",
        "lat": 25.5788,
        "lon": 91.8933,
    },
    {
        "state": "Meghalaya",
        "zone": "East",
        "city": "Khliehriat",
        "lat": 25.3341,
        "lon": 92.3582,
    },
    {
        "state": "Meghalaya",
        "zone": "West",
        "city": "Williamnagar",
        "lat": 25.5029,
        "lon": 90.6186,
    },
    {
        "state": "Meghalaya",
        "zone": "South",
        "city": "Baghmara",
        "lat": 25.2045,
        "lon": 90.6358,
    },
    {
        "state": "Meghalaya",
        "zone": "South-East",
        "city": "Ampati",
        "lat": 25.3400,
        "lon": 89.8787,
    },
    {
        "state": "Meghalaya",
        "zone": "South-West",
        "city": "Mawkyrwat",
        "lat": 25.3312,
        "lon": 91.2745,
    },
    # --- 17. MIZORAM ---
    {
        "state": "Mizoram",
        "zone": "North",
        "city": "Kolasib",
        "lat": 24.2183,
        "lon": 92.6775,
    },
    {
        "state": "Mizoram",
        "zone": "North-East",
        "city": "Champhai",
        "lat": 23.4735,
        "lon": 93.3323,
    },
    {
        "state": "Mizoram",
        "zone": "North-West",
        "city": "Mamit",
        "lat": 23.9298,
        "lon": 92.4920,
    },
    {
        "state": "Mizoram",
        "zone": "Center",
        "city": "Aizawl",
        "lat": 23.7271,
        "lon": 92.7176,
    },
    {
        "state": "Mizoram",
        "zone": "East",
        "city": "Serchhip",
        "lat": 23.3032,
        "lon": 92.8436,
    },
    {
        "state": "Mizoram",
        "zone": "West",
        "city": "Lunglei",
        "lat": 22.8876,
        "lon": 92.7441,
    },
    {
        "state": "Mizoram",
        "zone": "South",
        "city": "Saiha",
        "lat": 22.4862,
        "lon": 92.9734,
    },
    {
        "state": "Mizoram",
        "zone": "South-East",
        "city": "Lawngtlai",
        "lat": 22.5298,
        "lon": 92.8951,
    },
    {
        "state": "Mizoram",
        "zone": "South-West",
        "city": "Hnahthial",
        "lat": 23.0012,
        "lon": 92.9351,
    },
    # --- 18. NAGALAND ---
    {
        "state": "Nagaland",
        "zone": "North",
        "city": "Mon",
        "lat": 26.7490,
        "lon": 95.0097,
    },
    {
        "state": "Nagaland",
        "zone": "North-East",
        "city": "Tuensang",
        "lat": 26.2758,
        "lon": 94.8251,
    },
    {
        "state": "Nagaland",
        "zone": "North-West",
        "city": "Mokokchung",
        "lat": 26.3302,
        "lon": 94.5245,
    },
    {
        "state": "Nagaland",
        "zone": "Center",
        "city": "Wokha",
        "lat": 26.1042,
        "lon": 94.2635,
    },
    {
        "state": "Nagaland",
        "zone": "East",
        "city": "Kiphire",
        "lat": 25.8596,
        "lon": 94.7834,
    },
    {
        "state": "Nagaland",
        "zone": "West",
        "city": "Dimapur",
        "lat": 25.9094,
        "lon": 93.7267,
    },
    {
        "state": "Nagaland",
        "zone": "South",
        "city": "Kohima",
        "lat": 25.6751,
        "lon": 94.1086,
    },
    {
        "state": "Nagaland",
        "zone": "South-East",
        "city": "Phek",
        "lat": 25.6669,
        "lon": 94.4449,
    },
    {
        "state": "Nagaland",
        "zone": "South-West",
        "city": "Peren",
        "lat": 25.5262,
        "lon": 93.7431,
    },
    # --- 19. ODISHA ---
    {
        "state": "Odisha",
        "zone": "North",
        "city": "Rourkela",
        "lat": 22.2604,
        "lon": 84.8536,
    },
    {
        "state": "Odisha",
        "zone": "North-East",
        "city": "Balasore",
        "lat": 21.4942,
        "lon": 86.9314,
    },
    {
        "state": "Odisha",
        "zone": "North-West",
        "city": "Jharsuguda",
        "lat": 21.8552,
        "lon": 84.0042,
    },
    {
        "state": "Odisha",
        "zone": "Center",
        "city": "Angul",
        "lat": 20.8384,
        "lon": 85.1000,
    },
    {
        "state": "Odisha",
        "zone": "East",
        "city": "Kendrapada",
        "lat": 20.4996,
        "lon": 86.4251,
    },
    {
        "state": "Odisha",
        "zone": "West",
        "city": "Sambalpur",
        "lat": 21.4669,
        "lon": 83.9812,
    },
    {
        "state": "Odisha",
        "zone": "South",
        "city": "Berhampur",
        "lat": 19.3149,
        "lon": 84.7941,
    },
    {
        "state": "Odisha",
        "zone": "South-East",
        "city": "Puri",
        "lat": 19.8135,
        "lon": 85.8312,
    },
    {
        "state": "Odisha",
        "zone": "South-West",
        "city": "Koraput",
        "lat": 18.8133,
        "lon": 82.7118,
    },
    # --- 20. PUNJAB ---
    {
        "state": "Punjab",
        "zone": "North",
        "city": "Pathankot",
        "lat": 32.2643,
        "lon": 75.6420,
    },
    {
        "state": "Punjab",
        "zone": "North-East",
        "city": "Gurdaspur",
        "lat": 32.0419,
        "lon": 75.4053,
    },
    {
        "state": "Punjab",
        "zone": "North-West",
        "city": "Amritsar",
        "lat": 31.6340,
        "lon": 74.8723,
    },
    {
        "state": "Punjab",
        "zone": "Center",
        "city": "Ludhiana",
        "lat": 30.9010,
        "lon": 75.8573,
    },
    {
        "state": "Punjab",
        "zone": "East",
        "city": "Patiala",
        "lat": 30.3398,
        "lon": 76.3869,
    },
    {
        "state": "Punjab",
        "zone": "West",
        "city": "Firozpur",
        "lat": 30.9238,
        "lon": 74.6041,
    },
    {
        "state": "Punjab",
        "zone": "South",
        "city": "Bathinda",
        "lat": 30.2110,
        "lon": 74.9455,
    },
    {
        "state": "Punjab",
        "zone": "South-East",
        "city": "Sangrur",
        "lat": 30.2458,
        "lon": 75.8422,
    },
    {
        "state": "Punjab",
        "zone": "South-West",
        "city": "Abohar",
        "lat": 30.1444,
        "lon": 74.2024,
    },
    # --- 21. RAJASTHAN ---
    {
        "state": "Rajasthan",
        "zone": "North",
        "city": "Sriganganagar",
        "lat": 29.9079,
        "lon": 73.8772,
    },
    {
        "state": "Rajasthan",
        "zone": "North-East",
        "city": "Alwar",
        "lat": 27.5614,
        "lon": 76.6062,
    },
    {
        "state": "Rajasthan",
        "zone": "North-West",
        "city": "Bikaner",
        "lat": 28.0229,
        "lon": 73.3119,
    },
    {
        "state": "Rajasthan",
        "zone": "Center",
        "city": "Ajmer",
        "lat": 26.4499,
        "lon": 74.6399,
    },
    {
        "state": "Rajasthan",
        "zone": "East",
        "city": "Jaipur",
        "lat": 26.9124,
        "lon": 75.7873,
    },
    {
        "state": "Rajasthan",
        "zone": "West",
        "city": "Jaisalmer",
        "lat": 26.9157,
        "lon": 70.9083,
    },
    {
        "state": "Rajasthan",
        "zone": "South",
        "city": "Udaipur",
        "lat": 24.5854,
        "lon": 73.7125,
    },
    {
        "state": "Rajasthan",
        "zone": "South-East",
        "city": "Kota",
        "lat": 25.1755,
        "lon": 75.8388,
    },
    {
        "state": "Rajasthan",
        "zone": "South-West",
        "city": "Barmer",
        "lat": 25.7593,
        "lon": 71.4429,
    },
    # --- 22. SIKKIM ---
    {
        "state": "Sikkim",
        "zone": "North",
        "city": "Mangan",
        "lat": 27.5097,
        "lon": 88.5367,
    },
    {
        "state": "Sikkim",
        "zone": "North-East",
        "city": "Lachen",
        "lat": 27.7289,
        "lon": 88.5539,
    },
    {
        "state": "Sikkim",
        "zone": "North-West",
        "city": "Thangu Valley",
        "lat": 27.8542,
        "lon": 88.6678,
    },
    {
        "state": "Sikkim",
        "zone": "Center",
        "city": "Gangtok",
        "lat": 27.3389,
        "lon": 88.6065,
    },
    {
        "state": "Sikkim",
        "zone": "East",
        "city": "Pakyong",
        "lat": 27.2272,
        "lon": 88.6253,
    },
    {
        "state": "Sikkim",
        "zone": "West",
        "city": "Geyzing",
        "lat": 27.2917,
        "lon": 88.2526,
    },
    {
        "state": "Sikkim",
        "zone": "South",
        "city": "Namchi",
        "lat": 27.1683,
        "lon": 88.3582,
    },
    {
        "state": "Sikkim",
        "zone": "South-East",
        "city": "Rangpo",
        "lat": 27.1783,
        "lon": 88.5284,
    },
    {
        "state": "Sikkim",
        "zone": "South-West",
        "city": "Jorethang",
        "lat": 27.1264,
        "lon": 88.2934,
    },
    # --- 23. TAMIL NADU ---
    {
        "state": "Tamil Nadu",
        "zone": "North",
        "city": "Vellore",
        "lat": 12.9165,
        "lon": 79.1325,
    },
    {
        "state": "Tamil Nadu",
        "zone": "North-East",
        "city": "Chennai",
        "lat": 13.0827,
        "lon": 80.2707,
    },
    {
        "state": "Tamil Nadu",
        "zone": "North-West",
        "city": "Hosur",
        "lat": 12.7409,
        "lon": 77.8253,
    },
    {
        "state": "Tamil Nadu",
        "zone": "Center",
        "city": "Tiruchirappalli",
        "lat": 10.7905,
        "lon": 78.7047,
    },
    {
        "state": "Tamil Nadu",
        "zone": "East",
        "city": "Nagapattinam",
        "lat": 10.7656,
        "lon": 79.8424,
    },
    {
        "state": "Tamil Nadu",
        "zone": "West",
        "city": "Coimbatore",
        "lat": 11.0168,
        "lon": 76.9558,
    },
    {
        "state": "Tamil Nadu",
        "zone": "South",
        "city": "Kanyakumari",
        "lat": 8.0883,
        "lon": 77.5385,
    },
    {
        "state": "Tamil Nadu",
        "zone": "South-East",
        "city": "Rameswaram",
        "lat": 9.2881,
        "lon": 79.3129,
    },
    {
        "state": "Tamil Nadu",
        "zone": "South-West",
        "city": "Madurai",
        "lat": 9.9252,
        "lon": 78.1198,
    },
    # --- 24. TELANGANA ---
    {
        "state": "Telangana",
        "zone": "North",
        "city": "Adilabad",
        "lat": 19.6641,
        "lon": 78.5321,
    },
    {
        "state": "Telangana",
        "zone": "North-East",
        "city": "Mancherial",
        "lat": 18.8687,
        "lon": 79.4632,
    },
    {
        "state": "Telangana",
        "zone": "North-West",
        "city": "Nizamabad",
        "lat": 18.6725,
        "lon": 78.0941,
    },
    {
        "state": "Telangana",
        "zone": "Center",
        "city": "Hyderabad",
        "lat": 17.3850,
        "lon": 78.4867,
    },
    {
        "state": "Telangana",
        "zone": "East",
        "city": "Khammam",
        "lat": 17.2473,
        "lon": 80.1514,
    },
    {
        "state": "Telangana",
        "zone": "West",
        "city": "Sangareddy",
        "lat": 17.6192,
        "lon": 78.0813,
    },
    {
        "state": "Telangana",
        "zone": "South",
        "city": "Mahabubnagar",
        "lat": 16.7445,
        "lon": 77.9839,
    },
    {
        "state": "Telangana",
        "zone": "South-East",
        "city": "Nalgonda",
        "lat": 17.0503,
        "lon": 79.2662,
    },
    {
        "state": "Telangana",
        "zone": "South-West",
        "city": "Jogulamba Gadwal",
        "lat": 16.2307,
        "lon": 77.8091,
    },
    # --- 25. TRIPURA ---
    {
        "state": "Tripura",
        "zone": "North",
        "city": "Dharmanagar",
        "lat": 24.3685,
        "lon": 92.1672,
    },
    {
        "state": "Tripura",
        "zone": "North-East",
        "city": "Kanchanpur",
        "lat": 24.0152,
        "lon": 92.2341,
    },
    {
        "state": "Tripura",
        "zone": "North-West",
        "city": "Kailashahar",
        "lat": 24.3312,
        "lon": 92.0084,
    },
    {
        "state": "Tripura",
        "zone": "Center",
        "city": "Agartala",
        "lat": 23.8315,
        "lon": 91.2868,
    },
    {
        "state": "Tripura",
        "zone": "East",
        "city": "Ambassa",
        "lat": 23.9168,
        "lon": 91.8413,
    },
    {
        "state": "Tripura",
        "zone": "West",
        "city": "Khowai",
        "lat": 24.0754,
        "lon": 91.5971,
    },
    {
        "state": "Tripura",
        "zone": "South",
        "city": "Belonia",
        "lat": 23.2573,
        "lon": 91.4552,
    },
    {
        "state": "Tripura",
        "zone": "South-East",
        "city": "Sabroom",
        "lat": 23.5005,
        "lon": 91.7334,
    },
    {
        "state": "Tripura",
        "zone": "South-West",
        "city": "Udaipur",
        "lat": 23.5358,
        "lon": 91.4851,
    },
    # --- 26. UTTAR PRADESH ---
    {
        "state": "Uttar Pradesh",
        "zone": "North",
        "city": "Saharanpur",
        "lat": 29.9640,
        "lon": 77.5460,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "North-East",
        "city": "Gorakhpur",
        "lat": 26.7606,
        "lon": 83.3732,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "North-West",
        "city": "Moradabad",
        "lat": 28.8389,
        "lon": 78.7733,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "Center",
        "city": "Lucknow",
        "lat": 26.8467,
        "lon": 80.9462,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "East",
        "city": "Varanasi",
        "lat": 25.3176,
        "lon": 82.9739,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "West",
        "city": "Agra",
        "lat": 27.1767,
        "lon": 78.0081,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "South",
        "city": "Banda",
        "lat": 25.4797,
        "lon": 80.3364,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "South-East",
        "city": "Prayagraj",
        "lat": 25.4358,
        "lon": 81.8463,
    },
    {
        "state": "Uttar Pradesh",
        "zone": "South-West",
        "city": "Jhansi",
        "lat": 25.4484,
        "lon": 78.5685,
    },
    # --- 27. UTTARAKHAND ---
    {
        "state": "Uttarakhand",
        "zone": "North",
        "city": "Uttarkashi",
        "lat": 30.7268,
        "lon": 78.4354,
    },
    {
        "state": "Uttarakhand",
        "zone": "North-East",
        "city": "Pithoragarh",
        "lat": 29.5823,
        "lon": 80.2173,
    },
    {
        "state": "Uttarakhand",
        "zone": "North-West",
        "city": "Joshimath",
        "lat": 30.5574,
        "lon": 79.5670,
    },
    {
        "state": "Uttarakhand",
        "zone": "Center",
        "city": "Srinagar",
        "lat": 30.2230,
        "lon": 78.7820,
    },
    {
        "state": "Uttarakhand",
        "zone": "East",
        "city": "Champawat",
        "lat": 29.3365,
        "lon": 80.0911,
    },
    {
        "state": "Uttarakhand",
        "zone": "West",
        "city": "Dehradun",
        "lat": 30.3165,
        "lon": 78.0322,
    },
    {
        "state": "Uttarakhand",
        "zone": "South",
        "city": "Haridwar",
        "lat": 29.9457,
        "lon": 78.1642,
    },
    {
        "state": "Uttarakhand",
        "zone": "South-East",
        "city": "Haldwani",
        "lat": 29.2189,
        "lon": 79.5130,
    },
    {
        "state": "Uttarakhand",
        "zone": "South-West",
        "city": "Roorkee",
        "lat": 29.8543,
        "lon": 77.8880,
    },
    # --- 28. WEST BENGAL ---
    {
        "state": "West Bengal",
        "zone": "North",
        "city": "Siliguri",
        "lat": 26.7271,
        "lon": 88.3953,
    },
    {
        "state": "West Bengal",
        "zone": "North-East",
        "city": "Cooch Behar",
        "lat": 26.4830,
        "lon": 89.4560,
    },
    {
        "state": "West Bengal",
        "zone": "North-West",
        "city": "Malda",
        "lat": 25.2753,
        "lon": 88.1530,
    },
    {
        "state": "West Bengal",
        "zone": "Center",
        "city": "Bardhaman",
        "lat": 23.2324,
        "lon": 87.8615,
    },
    {
        "state": "West Bengal",
        "zone": "East",
        "city": "Krishnanagar",
        "lat": 23.4014,
        "lon": 88.5027,
    },
    {
        "state": "West Bengal",
        "zone": "West",
        "city": "Asansol",
        "lat": 23.6835,
        "lon": 86.9835,
    },
    {
        "state": "West Bengal",
        "zone": "South",
        "city": "Canning",
        "lat": 22.3150,
        "lon": 88.6677,
    },
    {
        "state": "West Bengal",
        "zone": "South-East",
        "city": "Kolkata",
        "lat": 22.5726,
        "lon": 88.3639,
    },
    {
        "state": "West Bengal",
        "zone": "South-West",
        "city": "Kharagpur",
        "lat": 22.3364,
        "lon": 87.3235,
    },
]